-- 開発用：ブログポストのRLSを一時的に無効化
ALTER TABLE blog_posts DISABLE ROW LEVEL SECURITY;

-- 必要に応じて他のテーブルも無効化
ALTER TABLE learning_records DISABLE ROW LEVEL SECURITY;
ALTER TABLE projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE skills DISABLE ROW LEVEL SECURITY;
ALTER TABLE contact_messages DISABLE ROW LEVEL SECURITY;